# version: '3.8'

# x-airflow-common: &airflow-common
#   build: .
#   env_file: .env
#   environment:
#     &airflow-common-env
#     AIRFLOW__CORE__EXECUTOR: LocalExecutor
#     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
#     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#     PYTHONPATH: /opt/airflow
#   volumes:
#     - ./airflow/dags:/opt/airflow/dags
#     - ./src:/opt/airflow/src
#     - ./data:/opt/airflow/data
#     - ./models:/opt/airflow/models
#     - ./dashboard:/opt/airflow/dashboard
#     - ./airflow/logs:/opt/airflow/logs
  
#   deploy:
#     resources:
#       reservations:
#         devices:
#           - driver: nvidia
#             count: 1
#             capabilities: [gpu]

# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: airflow
#       POSTGRES_PASSWORD: airflow
#       POSTGRES_DB: airflow
#     volumes:
#       - postgres-db-volume:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD", "pg_isready", "-U", "airflow"]
#       interval: 5s
#       retries: 5

#   chromadb:
#     image: chromadb/chroma:latest
#     ports:
#       - "8000:8000"
#     volumes:
#       - chroma-db-volume:/chroma/chroma
#     environment:
#       - IS_PERSISTENT=TRUE

#   airflow-init:
#     <<: *airflow-common
#     command: version
#     environment:
#       <<: *airflow-common-env
#       _AIRFLOW_DB_UPGRADE: 'true'
#       _AIRFLOW_WWW_USER_CREATE: 'true'
#       _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
#       _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
#     depends_on:
#       postgres:
#         condition: service_healthy

#   airflow-webserver:
#     <<: *airflow-common
#     command: webserver
#     ports:
#       - "8080:8080"
#     healthcheck:
#       test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
#       interval: 10s
#       timeout: 10s
#       retries: 5
#     depends_on:
#       airflow-init:
#         condition: service_completed_successfully


#   airflow-scheduler:
#     <<: *airflow-common
#     command: scheduler
#     depends_on:
#       airflow-init:
#         condition: service_completed_successfully


#   jupyter:
#     <<: *airflow-common
#     entrypoint: []
#     command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='admin'
#     ports:
#       - "8888:8888"
#     depends_on:
#       postgres:
#         condition: service_healthy
    
#     deploy: {}
#     environment:
#       PYTHONPATH: /opt/airflow
#       CUDA_VISIBLE_DEVICES: ""


#   streamlit:
#     <<: *airflow-common
#     entrypoint: []
#     command: streamlit run /opt/airflow/dashboard/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
#     ports:
#       - "8501:8501"
#     depends_on:
#       postgres:
#         condition: service_healthy
    
#     deploy: {}
#     environment:
#       PYTHONPATH: /opt/airflow
#       CUDA_VISIBLE_DEVICES: ""
  
#   api: 
#     <<: *airflow-common
#     container_name: sc-fastapi-api
#     entrypoint: [] 
#     command: ["/bin/bash", "-c", "uvicorn src.streaming.api:app --host 0.0.0.0 --port 80 --reload"] 

#     ports:
#       - "8001:80" 
      
#     deploy: {}
#     environment:
#       PYTHONPATH: /opt/airflow
#       CUDA_VISIBLE_DEVICES: ""
      
#     depends_on:
#       chromadb:
#         condition: service_started
        
# volumes:
#   postgres-db-volume:
#   chroma-db-volume:







version: '3.8'

x-airflow-common: &airflow-common
  build: .
  env_file: .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    PYTHONPATH: /opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
    - ./dashboard:/opt/airflow/dashboard
    - ./airflow/logs:/opt/airflow/logs

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
    - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-db-volume:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE

  # === APIs FastAPI ===
  producer_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8003:8000"

  processing_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn src.streaming.api:app --host 0.0.0.0 --port 8002
    ports:
      - "8004:8002"
  # === Airflow ===
  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
    depends_on:
      postgres:
        condition: service_healthy
      producer_api:
        condition: service_started
      processing_api:
        condition: service_started

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  jupyter:
    <<: *airflow-common
    entrypoint: []
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='admin'
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PYTHONPATH: /opt/airflow
      CUDA_VISIBLE_DEVICES: ""

  streamlit:
    <<: *airflow-common
    entrypoint: []
    command: streamlit run /opt/airflow/dashboard/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PYTHONPATH: /opt/airflow
      CUDA_VISIBLE_DEVICES: ""

  adminer:
      image: adminer
      restart: always
      ports:
        - "8081:8080"
      depends_on:
        - postgres

volumes:
  postgres-db-volume:
  chroma-db-volume:
